<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [4]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

Connecting and switching to connection 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [17]:
%%sql

select
orderdate,
DATE_TRUNC('month',orderdate):: DATE as Ordermonth,
sum(quantity*netprice*exchangerate) as netrevenue,
count(DISTINCT customerkey) as totalcustomers
from sales
group by orderdate

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

3294 rows affected.

       orderdate  ordermonth  netrevenue  totalcustomers
0     2015-01-01  2015-01-01    11640.80               9
1     2015-01-02  2015-01-01     5890.40               6
2     2015-01-03  2015-01-01    19796.67              11
3     2015-01-05  2015-01-01    12406.27               4
4     2015-01-06  2015-01-01    10349.87               5
...          ...         ...         ...             ...
3289  2024-04-16  2024-04-01    25098.99              14
3290  2024-04-17  2024-04-01    32938.67              22
3291  2024-04-18  2024-04-01    28408.76              25
3292  2024-04-19  2024-04-01    48386.88              19
3293  2024-04-20  2024-04-01    96879.43              35

[3294 rows x 4 columns]

In [21]:
%%sql

select
orderdate,
TO_CHAR(orderdate,'yyyy')
from sales
group by orderdate

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

3294 rows affected.

       orderdate to_char
0     2017-10-23    2017
1     2023-04-24    2023
2     2019-02-12    2019
3     2017-12-28    2017
4     2015-01-19    2015
...          ...     ...
3289  2023-10-19    2023
3290  2023-02-08    2023
3291  2017-10-29    2017
3292  2021-08-03    2021
3293  2017-07-01    2017

[3294 rows x 2 columns]